#!/usr/bin/env node

const {BncThreshSigClient} = require('../dist/src');
const client = new BncThreshSigClient();

const program = require('commander');

program
    .command('address')
    .option('-i, --index <index>', 'Address index')
    .action(async (options) => {
        await client.init();
        const address = client.getAddress(options.index);
        console.log(address);
    });

program
    .command('balance <address>')
    .action(async (address) => {
        await client.init();
        const balance = await client.getBalance(address);
        console.log(balance);
    });

program
    .command('transfer <from> <to> <amount>')
    .option('-m, --memo <memo>')
    .option('-a, --asset <asset>')
    .action(async (from, to, amount, options) => {
        await client.init();
        const transferResponse = await client.transfer(from, to, parseFloat(amount), options.asset || 'BNB', options.memo);
        console.log(transferResponse);
    });

program
    .command('transactions')
    .option('-a --address <address>')
    .option('-b --blockHeight <blockHeight>')
    .option('-s --startTime <startTime>', 'start time in Milliseconds (max 3 months ago)')
    .option('-e --endTime <endTime>', 'end time in Milliseconds')
    .option('-l --limit <limit>')
    .option('-o --offset <offset>')
    .option('-d --side <side>', 'transaction side, Allowed values: [RECEIVE, SEND]')
    .option('-a --asset <asset>')
    .option('-t --txType <txType>', 'transaction type. Allowed values: NEW_ORDER,ISSUE_TOKEN,BURN_TOKEN,LIST_TOKEN,CANCEL_ORDER,FREEZE_TOKEN,UN_FREEZE_TOKEN,TRANSFER,PROPOSAL,VOTE,MINT,DEPOSIT]')
    .action(async (options) => {
        await client.init();
        const txs = await client.getTransactions(options);
        console.log(JSON.stringify(txs, null, 2));
    });

program
    .command('buy_order <symbol> <price> <quantity>') // buy_order LCQ-AC5_BNB 0.001 10
    .action(async (symbol, price, quantity) => {
        await client.init();
        const transferResponse = await client.placeOrder(null, symbol,1,parseFloat(price),parseFloat(quantity));
        console.log(transferResponse);
    });

program
    .command('sell_order <symbol> <price> <quantity>')
    .action(async (symbol, price, quantity) => {
        await client.init();
        const transferResponse = await client.placeOrder(null, symbol,2,parseFloat(price),parseFloat(quantity));
        console.log(transferResponse);
    });

program
    .command('cancel_order <symbol> <ref_id>')
    .action(async (symbol, ref_id) => {
        await client.init();
        const transferResponse = await client.CancelOrder(null, symbol, ref_id);
        console.log(transferResponse);
    });

program.parse(process.argv);
